version: "3"
services:
  elasticsearch:
    image: elasticsearch:5.6.5-alpine
    networks:
      - mynet
  nginx:
    image: nginx:1.13.0-alpine
    ports:
      - 5601:80
    networks:
      - mynet
  kibana:
    image: kibana:5.6.5
    networks:
      - mynet
  logstash:
    image: logstash:5.6.5
    ports:
      - 5044:5044
      - 5000:5000
    volumes:
      - ./logstash.conf:/some/config-dir/logstash.conf
      - ./log/:/var/log
    command:
      - "-f"
      - "/some/config-dir/logstash.conf"
    networks:
      - mynet
networks:
  mynet:
