version: "3"
services:
  influxdb:
    image: influxdb:1.4-alpine
    networks:
      - mynet
  telegraf:
    image: telegraf:1.4-alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - mynet
  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - 3000:3000
    networks:
      - mynet
networks:
  mynet:
